/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,tsx,ts,jsx,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background:               '#0D0D0D',
        surface:                  '#1A1D22',
        'surface-container':      '#202329',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        primary:                  '#f2ca83',
        'on-primary':             '#412d00',
        'primary-container':      '#d4af6a',
        'on-primary-container':   '#5b4205',
        'primary-fixed':          '#ffdea5',
        'primary-fixed-dim':      '#e8c17a',
        'on-primary-fixed':       '#271900',
        'on-primary-fixed-variant': '#5c4205',
        secondary:                '#c4c6cd',
        'on-secondary':           '#2e3036',
        'secondary-container':    '#46494f',
        'on-secondary-container': '#b6b8bf',
        tertiary:                 '#bcd0ff',
        'on-tertiary':            '#1a3057',
        'tertiary-container':     '#a0b4e3',
        'outline-variant':        '#4e4639',
        'on-surface':             '#e5e2e1',
        'on-surface-variant':     '#d1c5b4',
        outline:                  '#9a8f80',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'margin-mobile':  '16px',
        'gutter':         '16px',
        'base':           '4px',
        'container-max':  '1200px',
      },
      fontFamily: {
        'display-lg':  ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg':     ['Inter', 'sans-serif'],
        'body-md':     ['Inter', 'sans-serif'],
        'label-md':    ['Inter', 'sans-serif'],
        'label-sm':    ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':    ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm':    ['11px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
